In [55]:
#imports
import pysat
import numpy as np
import matplotlib as plt
import pandas as pd
from pysat.solvers import Glucose3
from pysat.card import *
import time
import datetime
from numpy import savetxt

In [46]:
q=7
valtozok=[i+1 for i in range(q**2+q+1)]
#valtozok

In [47]:
ssolver = Glucose3()
normalforma=CNF()

In [48]:
#ne legyen olyan k, hogy van 2 változópár, amik egymástól k távolságra vannak és mind igaz értéket vesznek fel

for k in range(1, q**2+q+1, 1):
    for i in range(q**2+q+1):
        for j in range(q**2+q+1):
            if i != j:
                normalforma.append([-valtozok[i], -valtozok[(i+k)%(q**2+q+1)], -valtozok[j], -valtozok[(j+k)%(q**2+q+1)]])
            
#print(normalforma.clauses)

In [49]:
#pontosan q+1 1-es legyen a változók között
cnf=CardEnc.equals(lits=valtozok, bound=q+1, top_id=q**2+q+1)
for cl in cnf.clauses:
    normalforma.append(cl)

In [61]:
#beadom a sat-solvernek a normálformát
for kloz in normalforma.clauses:
    ssolver.add_clause(kloz)
    
# megoldás kiszámítása
ssolver.solve()
ans=ssolver.get_model()

#print(ans)

In [52]:
#kiprintelem a ciklikus véges projektív sík adjacenciamátrixát
megoldaslista=[]
for ele in ans[:q**2+q+1]:
    if ele<0:
        megoldaslista=megoldaslista+[0]
    else:
        megoldaslista=megoldaslista+[1]
print(megoldaslista)

[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]


In [60]:
megoldasmatrix=[]
for i in range(q**2+q+1):
    l=[]
    for j in range(q**2+q+1):
        l=l+[megoldaslista[(i+j)%(q**2+q+1)]]
    megoldasmatrix.append(l)

szep=np.array(megoldasmatrix)
print(szep)
#np.savetxt("ciklikus_"+str(q)+".csv", szep, fmt='%.0e')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#todo: valahogy szépen lementeni egy fájlba vagy kiprintelni azokat, amik már nem férnek el itt a képernyőn kiprintelve